### PR TITLE
Clr 9 design home page

### PR DESCRIPTION
**Pull request by chang2694**
screencapture-localhost-5173-2023-11-23-19_33_26
screencapture-localhost-5173-2023-11-23-19_32_06

### CODE REVIEW

**Review by tuanle03 — COMMENTED** [review]
Any ideas for long Titles? How will you display? Display all or just part of the title? @chang2694 @baoipc

**Review by baoipc — APPROVED** [review]
AI: Oke

**Comment by baoipc** [comment]
> Any ideas for long Titles? How will you display? Display all or just part of the title? @chang2694 @baoipc

just part + "..."

**Review by tuanle03 — APPROVED** [review]
LGTM

**Comment by chang2694** [comment]
> s? How will you display? Display all or just part of the

we will limit the title length

**Pull request merged**
